server:
  port: 9090

integration:
  zipcode:
    uri: http://localhost:8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

zipcode:
  ribbon:
    eureka:
      enabled: false
    DeploymentContextBasedVipAddresses: zip-code-api